10.8

diff --git a/.github/workflows/chek_pods.yaml b/.github/workflows/chek_pods.yaml
--- a/.github/workflows/chek_pods.yaml
+++ b/.github/workflows/chek_pods.yaml
@@ -17,14 +17,14 @@ jobs:
      #   echo "Проверка целевого сервера:"
       #  curl -v telnet://${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PORT }}
 
-    - name: Debug SSH connection
-      run: |
-        echo "Проверка доступа к бастиону:"
-        nc -zv -w 5 ${{ secrets.BASTION_IP }} ${{ secrets.BASTION_PORT }}
-    
-        echo "Проверка маршрута до целевого сервера:"
-        ssh -vvv -J ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_IP }}:${{ secrets.BASTION_PORT }} \
-        ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo Test" || echo "Failed"
+#    - name: Debug SSH connection
+ #     run: |
+  #      echo "Проверка доступа к бастиону:"
+   #     nc -zv -w 5 ${{ secrets.BASTION_IP }} ${{ secrets.BASTION_PORT }}
+    #
+     #   echo "Проверка маршрута до целевого сервера:"
+      #  ssh -vvv -J ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_IP }}:${{ secrets.BASTION_PORT }} \
+       # ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo Test" || echo "Failed"
 
 
     - name: Execute remote commands
